In [245]:
import pandas as pd

data = pd.read_csv("employees_100.csv")
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    str
 2   department          92 non-null     str
 3   city                90 non-null     str
 4   age                 94 non-null     float64
 5   salary              92 non-null     str
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    str
dtypes: float64(1), int64(4), str(5)
memory usage: 11.8 KB

In [246]:
data.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [247]:
data.info()
data.at[1,"name"]

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    str
 2   department          92 non-null     str
 3   city                90 non-null     str
 4   age                 94 non-null     float64
 5   salary              92 non-null     str
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    str
dtypes: float64(1), int64(4), str(5)
memory usage: 11.8 KB

'Kavya Malhotra'

In [248]:
data.set_index("employee_id").sort_index()

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
101,Ananya Malhotra,engineering,NaN,24.0,68591,2,8,0,2023-10-21
102,Rahul Menon,Engineering,Hyderabad,38.0,84870,11,6,15,2021-06-07
103,Ananya Nayak,Sales,Delhi,38.0,68490,9,6,6,2021-11-19
104,Ritu Iyer,Marketing,Bangalore,34.0,63574,8,7,20,2021-05-10
105,Vivek Pillai,Engineering,Pune,39.0,NaN,9,4,5,2024-06-05
...,...,...,...,...,...,...,...,...,...
192,Divya Verma,HR,Delhi,40.0,66363,12,7,13,2022-09-10
193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
194,Pooja Menon,Engineering,Chennai,NaN,76281,7,4,9,2022-07-28
195,Pooja Nair,Finance,NaN,33.0,69396,6,6,4,2023-01-13
196,Sanjay Pillai,Marketing,Bangalore,NaN,60503,0,8,15,2022-11-08

In [249]:
data.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [250]:
try:
    data = data.set_index("employee_id")
except KeyError:
    pass
data.iloc[0:10]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
181,Karan Rao,Marketing,NaN,22.0,50733,1,6,6,2020-04-05
111,Kavya Singh,Engineering,Delhi,23.0,NaN,1,5,10,2021-09-14
101,Ananya Malhotra,engineering,NaN,24.0,68591,2,8,0,2023-10-21

In [251]:
data.isnull().sum()

name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [252]:
data["age"].fillna(data["age"].mean())

employee_id
184    38.000000
154    30.861702
171    23.000000
146    28.000000
145    32.000000
         ...
161    22.000000
172    22.000000
115    43.000000
193    23.000000
152    44.000000
Name: age, Length: 100, dtype: float64

In [253]:
data.drop_duplicates(subset="employee_id",keep="first")
data.duplicated().sum()

KeyError: Index(['employee_id'], dtype='str')

In [ ]:
data["joining_date"] = pd.to_datetime(data["joining_date"])
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    str
 2   department          92 non-null     str
 3   city                90 non-null     str
 4   age                 94 non-null     float64
 5   salary              92 non-null     str
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(4), str(4)
memory usage: 10.8 KB

In [ ]:
data.rename(columns={"name":"Name"})

,employee_id,Name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [ ]:
data["salary"] = pd.to_numeric(data["salary"],errors="coerce")
data["annual salary"] = data["salary"]*12

In [ ]:
def categorize(num):
    if num > 5:
        return "expert"
    else:
        return "learner"

In [ ]:
data["status"] = data["experience"].apply(categorize)
data["perfomance_category"] = data["performance_score"].apply(lambda x: "excellent" if x>6 else("good" if x>4 else "needs improvement"))
data

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual salary,status,perfomance_category
employee_id,,,,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719.0,5,5,6,2021-07-02,848628.0,learner,good
154,Kavya Malhotra,engineering,Mumbai,NaN,77058.0,1,8,8,2024-02-05,924696.0,learner,excellent
171,Manish Desai,Data Science,Hyderabad,23.0,69911.0,0,6,18,2019-04-24,838932.0,learner,good
146,Neha Das,Engineering,Pune,28.0,69993.0,3,8,1,2022-12-13,839916.0,learner,excellent
145,Isha Nair,Data Science,NaN,32.0,88216.0,8,8,14,2019-11-25,1058592.0,expert,excellent
...,...,...,...,...,...,...,...,...,...,...,...,...
161,Nikhil Nair,MARKETING,Chennai,22.0,55740.0,0,5,22,2020-04-22,668880.0,learner,good
172,Neha Desai,HR,Chennai,22.0,52250.0,0,5,7,2020-11-14,627000.0,learner,good
115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06,NaN,expert,needs improvement
193,Priya Nayak,HR,NaN,23.0,56821.0,3,9,16,2019-08-07,681852.0,learner,excellent
152,Kavya Joshi,Marketing,Delhi,44.0,69499.0,10,7,4,2022-03-25,833988.0,expert,excellent

In [ ]:
raw_codes = {"engineering":"ENG","datascience":"DS","HR":"Hr","finance":"FN","marketing":"MK","Sales":"SL"}

codes = {k.lower().replace(" ",""):v for k, v in raw_codes.items()}

data["Department_codes"] = data["department"].str.replace(" ","").str.lower().map(codes)
data

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,Department_codes
employee_id,,,,,,,,,,
101,Ananya Malhotra,engineering,NaN,24.0,68591,2,8,0,2023-10-21,ENG
102,Rahul Menon,Engineering,Hyderabad,38.0,84870,11,6,15,2021-06-07,ENG
103,Ananya Nayak,Sales,Delhi,38.0,68490,9,6,6,2021-11-19,SL
104,Ritu Iyer,Marketing,Bangalore,34.0,63574,8,7,20,2021-05-10,MK
105,Vivek Pillai,Engineering,Pune,39.0,NaN,9,4,5,2024-06-05,ENG
...,...,...,...,...,...,...,...,...,...,...
192,Divya Verma,HR,Delhi,40.0,66363,12,7,13,2022-09-10,Hr
193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07,Hr
194,Pooja Menon,Engineering,Chennai,NaN,76281,7,4,9,2022-07-28,ENG
195,Pooja Nair,Finance,NaN,33.0,69396,6,6,4,2023-01-13,FN
196,Sanjay Pillai,Marketing,Bangalore,NaN,60503,0,8,15,2022-11-08,MK

In [ ]:
data.reset_index()
data.sort_values(by="salary",ascending=False)

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
158,Tanvi Malhotra,NaN,Mumbai,32.0,"88,366",11,5,19,2021-02-26
158,Tanvi Malhotra,NaN,Mumbai,32.0,"88,366",11,6,17,2021-02-26
124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
102,Rahul Menon,Engineering,Hyderabad,38.0,84870,11,6,15,2021-06-07
...,...,...,...,...,...,...,...,...,...
143,Neha Rao,Sales,Hyderabad,37.0,NaN,11,6,11,2023-05-15
120,Isha Gupta,Marketing,Mumbai,26.0,NaN,6,5,14,2018-03-27
179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
157,Ananya Rao,Engineering,Mumbai,25.0,NaN,2,5,8,2022-04-07
115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06

In [257]:
data["experience_rank"] = data["experience"].rank(ascending=False,method="min")
data.sort_values("experience_rank")

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,experience_rank
employee_id,,,,,,,,,,
155,Sanjay Das,NaN,Bangalore,45.0,74505,17,6,10,2022-06-22,1.0
192,Divya Verma,HR,Delhi,40.0,66363,12,7,13,2022-09-10,2.0
115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06,2.0
143,Neha Rao,Sales,Hyderabad,37.0,NaN,11,6,11,2023-05-15,4.0
158,Tanvi Malhotra,NaN,Mumbai,32.0,"88,366",11,5,19,2021-02-26,4.0
...,...,...,...,...,...,...,...,...,...,...
116,Rohan Verma,Engineering,Chennai,23.0,62693,0,4,8,2018-08-17,86.0
161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22,86.0
130,Arjun Nair,Finance,Pune,22.0,60514,0,9,24,2019-06-17,86.0
142,Shreya Das,HR,Pune,22.0,56504,0,7,2,2021-06-19,86.0
172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14,86.0

In [272]:
data.groupby(["department"])["age"].apply(lambda x: x.mode())

department
 HR           0    32.0
 Marketing    0    25.0
Data Science  0    22.0
              1    23.0
              2    26.0
              3    27.0
              4    28.0
              5    30.0
              6    31.0
              7    32.0
              8    38.0
              9    41.0
Engineering   0    38.0
FINANCE       0    35.0
Finance       0    24.0
HR            0    22.0
              1    33.0
MARKETING     0    22.0
Marketing     0    22.0
SALES         0    37.0
Sales         0    23.0
              1    25.0
              2    26.0
              3    29.0
              4    30.0
              5    34.0
              6    37.0
              7    38.0
engineering   0    24.0
Name: age, dtype: float64